#cloud-config
hostname: ns-00
fqdn: ns-00.nip.io

package_update: true
package_upgrade: true

packages:
  - "@development-tools"
  - bind-utils
  - btop
  - bzip2
  - curl
  - file
  - git-lfs
  - golang
  - htop
  - iputils
  - jq
  - neovim
  - net-tools
  - netcat
  - python3
  - python3-devel
  - python3-pip
  - python3-virtualenv
  - ripgrep
  - rsync
  - socat
  - sudo
  - tar
  - tcpdump
  - tmux
  - tree
  - unzip
  - zstd

users:
  - name: cunnie
    gecos: Brian Cunnie
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: wheel
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519
        AAAAC3NzaC1lZDI1NTE5AAAAIKoPHfGEM2RMBpcW2ZzKUmTNbweJbzfz6Y/EZ+WXJDVz

write_files:
  - path: /etc/systemd/system/sslip.io-dns.service
    content: |
      [Unit]
      Description=sslip.io DNS server
      Documentation=https://sslip.io/

      # start after agent so public IPs are assigned because
      # systemd-resolved prevents binding to INADDR_ANY
      After=droplet-agent.service do-agent.service

      [Service]
      ExecStart=/usr/bin/sslip.io-dns-server
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    permissions: "0644"

runcmd:
  # reserved IPv6 won't work until I manually add it to eth0:
  - nmcli connection modify "cloud-init ens3" +ipv6.addresses "2400:6180:0:d2:0:2:e3e7:0/64"
  - curl -L -o /usr/bin/sslip.io-dns-server https://github.com/cunnie/sslip.io/releases/download/5.1.4/sslip.io-dns-server-linux-amd64
  - chmod +x /usr/bin/sslip.io-dns-server
  - systemctl daemon-reload
  - systemctl enable sslip.io-dns.service
  # Fix "[systemd] Failed Units: 1 systemd-binfmt.service"
  - systemctl disable systemd-binfmt.service

power_state:
  mode: reboot
  message: |
    Rebooting to pick up new kernel, if any
  timeout: 60
  condition: true
